# Generated by Django 5.0.6 on 2024-07-18 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
