# Generated by Django 5.0.6 on 2024-07-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_category_options"),
        ("product", "0002_alter_category_options_alter_product_image"),
    ]

    operations = []
