# Generated by Django 5.0.6 on 2024-07-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_user_followers_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="activate",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="description",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_private",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_reported",
        ),
        migrations.RemoveField(
            model_name="user",
            name="posts_count",
        ),
        migrations.DeleteModel(
            name="Relation",
        ),
    ]
